### ISSUE TITLE
Command to recreate the envs

### ISSUE THREAD

**Issue by hackaugusto** [tkf/emacs-python-environment#16]
I'm running archlinux and get frequent updates, sometimes the `python` binary from the virtualenv will be incompatible with the newly installed `/usr/lib/libpython3.so` and I need to recreate the venv by hand (removing the old one and restarting emacs).

A helper command would be nice.

**Comment by syohex** [comment]
How about following command ?

```lisp
(defun jedi:reinstall-server ()
  (interactive)
  (let ((root (python-environment-root-path jedi:environment-root)))
    (when (yes-or-no-p
           (format "Reinstall jedi server environment(%s) ?" (abbreviate-file-name root)))
      (delete-directory root t)
      (jedi:install-server))))
```

**Comment by hackaugusto** [comment]
Great! Thanks for the solution

**Comment by syohex** [comment]
I have added that command at https://github.com/tkf/emacs-jedi/pull/279.
